### ISSUE TITLE
大佬，我想用你这vitepress文档进行二次开发，但是运行过程中遇到点问题，请教您一下

### ISSUE THREAD

**Issue by 251205668** [anncwb/vue-vben-admin-doc#26]
![](https://image.yangxiansheng.top/img/20210629212156.png?imglist)

**Comment by watonyweng** [comment]
@251205668 please upgrade vite-plugin-components version

**Comment by adokeHYF** [comment]
是由于你的nodejs 版本太低导致的，有两种办法可以解决
1.  升级nodejs 版本到最新的稳定版，经过我测试，应该至少到14
2. 修改 
![image](https://user-images.githubusercontent.com/29793946/134442882-cc31df51-686c-4014-92e4-ce17e58732db.png)
这个文件中 的476行改成 
![image](https://user-images.githubusercontent.com/29793946/134442954-6d04c6fb-65f6-48d3-998e-0e25811bb04e.png)

这样就可以强制启动了
